### ISSUE TITLE
npm run start报错

### ISSUE THREAD

**Issue by seven-cm** [fireyy/react-antd-admin#17]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Program Files\react\react-antd-admin\npm-debug.log

**Comment by fireyy** [comment]
抱歉，文档忘记更新了，开发应该是执行 `npm run dev`
