### ISSUE TITLE
webpack definePlugin not work

### ISSUE THREAD

**Issue by jweboy** [fireyy/react-antd-admin#18]
new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify('production')
  })
我按照你的方式分别在dev和pro配置文件下 添加了这个配置，但是在srever.js判断不起作用，仍然是undefined我想问是不是还需要添加其他配置来解析？

**Comment by fireyy** [comment]
@jweboy 这两个文件原来就有 这个配置，你说的 srever.js 是指 `devServer.js` 吗？
