### ISSUE TITLE
按照实例步骤安装后，运行报错啊。  

### ISSUE THREAD

**Issue by lllyyylll2** [fireyy/react-antd-admin#2]
ERROR in ./src/index.js  
Module parse failed: d:\Project\NODE\react-antd-admin\src\index.js Unexpected token (27:2)  
You may need an appropriate loader to handle this file type.  

我知道是jsx的原因，代码中那里配置呢？

**Comment by fireyy** [comment]
看看 babel 是否安装成功

**Comment by lllyyylll2** [comment]
我试过了，因为的webpack.config.js中的include的原因，去掉就可以了。

**Comment by fireyy** [comment]
是 include 里的 `__dirname` 获取有问题？
