### ISSUE TITLE
Error at logout

### ISSUE THREAD

**Issue by KirillYoYo** [fireyy/react-antd-admin#22]
Error Cannot read property 'stop' of null at logout or at change page at first run

**Comment by fireyy** [comment]
more detail or take a screenshot, please

**Comment by thienlhh** [comment]
I found this error relate g2-moblie, remove it then error has gone

**Comment by fireyy** [comment]
Thank you, I will check it soon.

**Comment by fireyy** [comment]
g2-mobile relate error: https://github.com/antvis/g2-mobile/issues/9.
Wait for fix

**Comment by fireyy** [comment]
14a5cb0 lock g2-mobile version to 2.1.13

**Comment by KirillYoYo** [comment]
Sorry, but it doesent help me
I pulled issue, removed g2-mobile from node modules, npm i g2-mobile
new errors became 
![err](https://user-images.githubusercontent.com/26794095/27244984-2c4ffc7e-52fa-11e7-9fdc-df1b395923db.png)

**Comment by fireyy** [comment]
I create new issues about first two warning, will fix it soon.
The warn in MapMarker, I think is a third party package u installed.
May be give more infomation about it.

**Comment by KirillYoYo** [comment]
Oh, its true about MapMarker its my code
Thanks
