### ISSUE TITLE
版本比较老了，更新一下代码？

### ISSUE THREAD

**Issue by xiaoming8185620** [fireyy/react-antd-admin#3]
npm install 之后发现依然有不少库没有装。

**Comment by fireyy** [comment]
最近比较忙，我找空更新一下

**Comment by leosxie** [comment]
我已经基于这个用react+redux+immutable+react-router弄了一套后台啦，开发起来还是蛮爽的，还是一点aop的切入登录控制不是弄的很好

**Comment by xiaoming8185620** [comment]
谢谢@lovesmilesha 我先看下试试。

**Comment by yhhwpp** [comment]
@lovesmilesha  后台代码能否共享下
