### ISSUE TITLE
confused with router

### ISSUE THREAD

**Issue by alwqx** [fireyy/react-antd-admin#33]
Hi, I add a new component `Register` in **src/views/Register/index.jsx**, I add the route map in **src/route/index.js**:
```
const routes = (
  <Switch>
    <Route path="/login" component={Login}/>
    <Route path="/register" component={Register}/>
    <Route path="/" component={Layout}/>
  </Switch>
);
```
Then, I add a button to get to the register page when clicked, however I can not finish it.I try below ways:

## use this.props
I bind a `toRegister` function to a button in `src/views/Login` component.
```
toRegister () {
    const { history } = this.props
    history.replace("/register")
  }
```
this throw exception: `Uncaught TypeError: Cannot read property 'replace' of undefined`

## use hashHistory from react-router
I import hashHistory form react-router in `src/views/Login`
```
import { hashHistory } from 'react-router';
```
But I got `82:6-17 "export 'hashHistory' was not found in 'react-router'`

I notice this project uses new route ways with latest react version. I am not familiar with route. So can you help me how to route from Login page to Register page when click button in Login page. Thanks.

**Comment by alwqx** [comment]
I use
```
window.location.hash = "#/login"
window.location.hash = "#/register"
```
It can work but does not use `react-router` or `react-router-dom`

**Comment by fireyy** [comment]
To use `history` in `this.props`, you can easy wrap `Login` component with `withRouter`.

Edit `src/views/Login/index.jsx`,

First, import

```
import { withRouter } from 'react-router-dom';
```

Then, wrap

```
export default connect(mapStateToProps, mapDispatchToProps)(Login)
```

to

```
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(Login))
```

Finally, `this.props.history` works.
