### ISSUE TITLE
webpack source map doesent work?

### ISSUE THREAD

**Issue by KirillYoYo** [fireyy/react-antd-admin#36]

**Comment by KirillYoYo** [comment]
maybe this issue true?
https://stackoverflow.com/questions/30870830/how-do-i-generate-sourcemaps-when-using-babel-and-webpack

**Comment by fireyy** [comment]
It works, whether dev and prod. Could you give more information about it.

**Comment by KirillYoYo** [comment]
![7777](https://user-images.githubusercontent.com/26794095/28263410-b1dd74c4-6af7-11e7-9b83-f3a29313d7fa.png)
npm run dev
webpack confing not changed

**Comment by fireyy** [comment]
webpack config？
Sorry, I can't understand...

**Comment by KirillYoYo** [comment]
Sorry, I means css CSS sourcemaps
like https://medium.com/@toolmantim/getting-started-with-css-sourcemaps-and-in-browser-sass-editing-b4daab987fb0

**Comment by fireyy** [comment]
I see, the `cssSourceMap` options is set to false by default. I will test if it works soon

**Comment by fireyy** [comment]
You can enable CSS sourcemaps, modify `config/index.js`

change

```
cssSourceMap: false
```

to

```
cssSourceMap: true
```
