### ISSUE TITLE
close

### ISSUE THREAD

**Issue by mcuking** [fireyy/react-antd-admin#39]
close

**Comment by fireyy** [comment]
`code-split` 分支包含了你需要的功能，但是 Code Split 跟 Ant.design 的 `babel-plugin-import`并存，目前有未解决的bug，具体可以看[这里](https://github.com/ant-design/babel-plugin-import/issues/120)，会导致打出来的分包过大。

**Comment by mcuking** [comment]
看来只能等bable-plugin-import及时修复这个问题了，另外对你们这么快响应我的问题感到很是惊喜呀，看来我的选择没错，哈哈哈😄
