### ISSUE TITLE
这套脚手架怎么切换页面？

### ISSUE THREAD

**Issue by yipanbo** [fireyy/react-antd-admin#4]
你好，我刚接触reactjs，用了你的脚手架，但是有一点不太清楚，不知道怎么切换页面。
我想实现：点击左侧的菜单，右边的内容改变。
应该是跟react-router和redux有关，但是始终没反应，也没报错。
求大神指导，谢谢！

**Comment by fireyy** [comment]
在 `index.js` 里定义新的页面路由，具体可以看 `react-router` 的文档
接着换掉左侧菜单的链接为你新定义的路由地址

**Comment by yipanbo** [comment]
@fireyy 我现在说一下我的理解，大神看下对不对。
1.在index.js中添加新路由：比如这样：
`<Provider store={store}>
    <Router history={history}>
        <Route path="/" onEnter={validate}>
          <IndexRedirect to="home" />
          <Route component={App}>
            <Route path="home" component={Home}/>
            **<Route path="menu301" component={Menu301} />**
          </Route>
          <Route path="login" component={Login}/>
        </Route>
      </Router>
  </Provider>`
其中，`<Route path="menu301" component={Menu301} />`是我添加的路由信息。
2.在sidebar的index.js文件中添加上面的链接，如下：
`render () {
    const { items } = this.props
    let openKey = []
    const menu = items.map((item) => {
      openKey.push('sub'+item.key)
      return (
        <SubMenu
          key={'sub'+item.key}
          title={<span><Icon type={item.icon} />{item.name}</span>}
        >
          {item.child.map((node) => {
            return (
              <Menu.Item key={'menu'+node.key}>
                **<Link to={'menu'+node.key}>{node.name}
                </Link>**
              </Menu.Item>
            )
          })}
        </SubMenu>
      )
    });
    return (
      <aside className="ant-layout-sider">        
        <Menu
          mode="inline" theme="light" openKeys={openKey}
          onClick={this.menuClickHandle}
          style={{borderRight: 0}}
        >
          {menu}
        </Menu>
      </aside>
    )
  }`
其中，`<Link to={'menu'+node.key}>{node.name}</Link>`是我添加的，以前是没有这个Link的。
这样，确实可以实现页面的跳转，主要依靠的是Link组件。
现在我想请教大神，这样实现有问题么？如果有问题的话，有没有更好的实现方法呢？谢谢！
可能代码格式有点混乱，不知道这个编辑器怎么换行，大神先凑合看下。

**Comment by fireyy** [comment]
就是这个思路

**Comment by yipanbo** [comment]
非常感谢！还有个问题，一会我再开个issue吧。

**Comment by alwqx** [comment]
我也是初学者，准备定制这个手脚架。
[基于现在最新的代码](https://github.com/fireyy/react-antd-admin/tree/498654b846a7050be540a58db2829f7a2a56a644)，关于左侧sideBar和路由部分我不太明白，从代码看，现在的路由是在`src/api/mock`中指定的，而我尝试修改`src/route/index.js`中的路由配置部分（**只加了TestPage2**）：
```
const routes = (
  <Route path="/" onEnter={validate}>
    <IndexRedirect to="home" />
    <Route component={App}>
      <Route path="home" component={Home}/>
      <Route path="form" component={Form}/>
      <Route path="table" component={Table}/>
      <Route path="page2" component={Page2}/>
      <Route path="TestPage2" component={Page2}/>
    </Route>
    <Route path="login" component={Login}/>
  </Route>
);
```
发现前端没有变化，希望请教下如何取消使用mock中的路由数据，而直接用`src/route`中的路由配置？

**Comment by fireyy** [comment]
@adolphlwq 这两者不一样，`src/api/mock` 里的数据代表模拟服务端下发的 menu 数据，用于页面显示，而 `src/route` 里代表的是这个应用支持的所有路由配置，所以新增一个页面的顺序是：

1. 在 `src/route` 里配置新 `<Route />`
2. 如果这个页面需要在 `sideBar` 显示，则在 `src/api/mock/menu.js` 里添加一个菜单项
