### ISSUE TITLE
npm run build 提示内存溢出是怎么回事啊

### ISSUE THREAD

**Issue by LDD123** [fireyy/react-antd-admin#40]
需要增大node.js内存，吗，怎么增加啊

**Comment by fireyy** [comment]
能把详细的错误贴上来或者截图吗？

**Comment by LDD123** [comment]
![qq 20171016091520](https://user-images.githubusercontent.com/11335860/31591520-0dabb6ec-b253-11e7-8860-11423f10b726.png)

**Comment by LDD123** [comment]
windows x64    node  6.10.3  npm 3.10.10
![qq 20171016091520](https://user-images.githubusercontent.com/11335860/31591536-34c49e60-b253-11e7-971c-27367e5b3cda.png)

**Comment by LDD123** [comment]
不是您的这个项目，是以您的项目为框架，我们写的别的项目

**Comment by fireyy** [comment]
可以尝试[增大使用内存](https://github.com/nodejs/node/wiki/Frequently-Asked-Questions)，或者可以用以下办法取消 source map, 修改 `build/webpack.prod.conf.js`

```
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
}),
```

修改为

```
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: false
}),
```

**Comment by LDD123** [comment]
我的文件目录好像没有您说的这个文件

![image](https://user-images.githubusercontent.com/11335860/31591947-3e99e806-b257-11e7-8f6d-857aa87f62ba.png)

**Comment by fireyy** [comment]
看目录结构，不像我这个项目...

你看看 `webpack.config.js`

**Comment by LDD123** [comment]
module.exports = (webpackConfig) => {
  // FilenameHash
  webpackConfig.output.chunkFilename = '[name].[hash].js' // http://webpack.github.io/docs/configuration.html#output-chunkfilename

  // ClassnameHash
  const cssLoaderOption = {
    importLoaders: 1,
    modules: true,
    localIdentName: '[hash:base64:5]',
  }
  const cssLoaders = webpackConfig.module.loaders[3].loader.split('!')
  cssLoaders[1] = `css?${JSON.stringify(cssLoaderOption)}`
  webpackConfig.module.loaders[3].loader = cssLoaders.join('!')

  return webpackConfig
}

**Comment by fireyy** [comment]
看文件结构，打包部分的代码不像我这个项目，似乎使用的是 [roadhog](https://github.com/sorrycc/roadhog), 建议去看看文档
