### ISSUE TITLE
主页面刷新问题

### ISSUE THREAD

**Issue by yipanbo** [fireyy/react-antd-admin#5]
问题描述：我通过登陆界面登录系统，进入主页面，然后刷新页面，此时页面又到了登录界面。
环境：chrome 51.0.2704.106 m浏览器，  win10系统
这个不知道是bug还是什么，但总感觉不应该这样的，求大神指教，谢谢！

**Comment by fireyy** [comment]
登陆态需要server支持，项目里只是做了一个简单的node server设置了一个cookie
