### ISSUE TITLE
Does not work in production

### ISSUE THREAD

**Issue by kachkaev** [fireyy/react-antd-admin#6]
`NODE_ENV=production PORT=3000 npm start` returns this HTML:

```html
<html>
    <head>
        <title>React Ant.Design Admin UI</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
        <div id="root">
        </div>
    </body>
    <script src="/dist/bundle.js"></script>
</html>
```

However, there's no `/dist/bundle.js`. It would be nice if the app had a build script too - this can be useful to see how big the production `bundle.js` would be (the development version is 6MB+).

**Comment by fireyy** [comment]
Thank you, I will fix later.

**Comment by fireyy** [comment]
run build
```
npm run build
```

run demo

```
npm run demo
```

**Comment by kachkaev** [comment]
Thank you! `639 KB` vendor and `24KB` main.
